[[redirects]]
  from = "/*"
  to = "/initialgrid.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/mobile-warning.html"
  status = 200
  conditions = {UserAgent = ["Mobi", "Android", "iPhone"]}
